version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
     - "9092:9092"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
  producer:
    build: ./scanner
    command: sh -c "./wait-for-it.sh -s kafka:9092 -- python app.py"
    volumes:
     - ./scanner:/src
    links:
     - kafka
  consumer:
    build: ./scanner
    command: sh -c "./wait-for-it.sh -s kafka:9092 -- python app2.py"
    volumes:
     - ./scanner:/src
    links:
     - kafka
